Fix tests: Do not test different id in test_dir
Looks like the python interpreter uses the same id if it's available, so
this test fails randomly, depending on memory management.

".../ana-0.06/test.py", line 113, in test_dir
    self.assertNotEqual(old_id, id(two))
AssertionError: 140642905866320 == 140642905866320

This patch just removes the check because we cannot be sure that they
are different.